![Astrofisica Computacional](../../../new_logo.png)

---
# 01. Introduction to `NumPy`

## Dr. rer. nat. Jose Ivan Campos Rozo<sup>1,2</sup>

1. Astronomical Institute of the Czech Academy of Sciences\
   Department of Solar Physics\
   Ondřejov, Czec Republic

2. Observatorio Astronómico Nacional\
   Facultad de Ciencias\
   Universidad Nacional de Colombia

e-mail: jicamposr@unal.edu.co & rozo@asu.cas.cz)

---

<h2 style="white-space:nowrap;margin-bottom: 1px;margin-top: 20px;"><strong>About This Notbook</strong></h2>
        <p style="text-align:justify;margin-top: 5px;margin-bottom: 10px;font-size: 32px;">In this notebook we present a short and fast introduction to the <code>numpy</code> package.</p>
---

In [4]:
import numpy as np
import sys

print(f"Python version:  {sys.version}\n"
      f"NumPy version:   {np.__version__}")


Python version:  3.12.3 (main, Jan 22 2026, 20:57:42) [GCC 13.3.0]
NumPy version:   2.4.2


## Arrays in NumPy: `ndarray`

A 1-dimensional array

In [5]:
a = np.array([1., 2., 3., 4., 5.])
a

array([1., 2., 3., 4., 5.])

In [6]:
type(a)

numpy.ndarray

## Properties of an array

In [7]:
a.size  # Gives the number of elements in the array

5

In [8]:
a.ndim  # Number of dimensions of the array

1

In [9]:
a.shape  # Shape of the array

(5,)

In [10]:
a.dtype  # Type of the elements in the array

dtype('float64')

Multi-dimensional Arrays

In [11]:
b = np.array([[1., 2., 3.],[4., 5., 6.], [7., 8., 9.]])
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [12]:
print(type(b))
print(b.size)
print(b.ndim)
print(b.shape)
print(b.dtype)

<class 'numpy.ndarray'>
9
2
(3, 3)
float64


## Array Methods

In [13]:
a

array([1., 2., 3., 4., 5.])

Minimum, maximum and mean

In [14]:
a.min(), a.max(), a.mean()

(np.float64(1.0), np.float64(5.0), np.float64(3.0))

Sum of elements

In [15]:
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [16]:
b.sum()

np.float64(45.0)

In [17]:
b.sum(axis=0)

array([12., 15., 18.])

In [18]:
b.sum(axis=1)

array([ 6., 15., 24.])

In [19]:
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [20]:
b.T # Transpose of b

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [21]:
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [22]:
b = b.T

In [23]:
b

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

## Operations with Arrays

In [24]:
a

array([1., 2., 3., 4., 5.])

In [25]:
a + 5.

array([ 6.,  7.,  8.,  9., 10.])

In [26]:
a*np.pi/2.

array([1.57079633, 3.14159265, 4.71238898, 6.28318531, 7.85398163])

$a^e$

In [27]:
a**np.e

array([ 1.        ,  6.58088599, 19.81299075, 43.30806043, 79.43235917])

$e^a$

In [28]:
np.e**a

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

Products of arrays

In [29]:
a

array([1., 2., 3., 4., 5.])

In [30]:
a * a  # Element-wise product

array([ 1.,  4.,  9., 16., 25.])

In [31]:
a @ a  # Matrix Product

np.float64(55.0)

In [32]:
np.dot(a,a) # Equivalent form of the matrix product

np.float64(55.0)

Other operations

In [33]:
a

array([1., 2., 3., 4., 5.])

In [34]:
a < 3

array([ True,  True, False, False, False])

In [35]:
a == 4

array([False, False, False,  True, False])

Other operations

In [36]:
(a > 3) & (a < 5)  # bitwise AND

array([False, False, False,  True, False])

In [37]:
a < np.array([2, 3, 5, 2, 1])

array([ True,  True,  True, False, False])

In [38]:
a

array([1., 2., 3., 4., 5.])

In [39]:
a < 3

array([ True,  True, False, False, False])

In [40]:
np.sum(a < 3) 

np.int64(2)

## Indices and Slicing

In [41]:
a

array([1., 2., 3., 4., 5.])

In [42]:
a[0]  # Remember that indices start at 0

np.float64(1.0)

In [43]:
a[-1]  # Index [-1] refers to the last element

np.float64(5.0)

In [44]:
a[2:6] # Indices [start:end]

array([3., 4., 5.])

In [45]:
a[2:6:2]  # Indices [start:end:step]

array([3., 5.])

In [46]:
a[::-1]  # Reverse an array

array([5., 4., 3., 2., 1.])

### Indixing and Slicing in Multiple Dimensions

In [47]:
b

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [48]:
b[0]

array([1., 4., 7.])

In [49]:
b[2, 2]

np.float64(9.0)

In [50]:
b[:,1] # The symbol `:` selects the whole axis

array([4., 5., 6.])

In [51]:
b[0, 1:4]

array([4., 7.])

In [52]:
b[:, 1:3]  

array([[4., 7.],
       [5., 8.],
       [6., 9.]])

In [53]:
b[:, 0:5:2]

array([[1., 7.],
       [2., 8.],
       [3., 9.]])

In [54]:
b[::-1]  # reverses axis 0

array([[3., 6., 9.],
       [2., 5., 8.],
       [1., 4., 7.]])

In [55]:
b[::-1, ::-1]  # reverses both axes

array([[9., 6., 3.],
       [8., 5., 2.],
       [7., 4., 1.]])

## Advanced Indexing

In [56]:
d = np.array([10, 15, 2., 5, 10, 2, 1])
d

array([10., 15.,  2.,  5., 10.,  2.,  1.])

In [57]:
mask = np.array([True, False, False, True, False, True, True])
mask

array([ True, False, False,  True, False,  True,  True])

In [58]:
d[mask]

array([10.,  5.,  2.,  1.])

In [59]:
d[[0,3,5,6]]

array([10.,  5.,  2.,  1.])

In [60]:
d[[1, 3, 1, 6]]

array([15.,  5., 15.,  1.])

## Helper Functions to Create Arrays

In [61]:
np.arange(7) # Creates array from a range of integers

array([0, 1, 2, 3, 4, 5, 6])

In [62]:
np.arange(2,7)

array([2, 3, 4, 5, 6])

In [63]:
np.arange(2,7,2)

array([2, 4, 6])

In [64]:
np.linspace(1, 5, 10) #[start, end, number of points in the interval]

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [65]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [66]:
np.ones(10, dtype='i') # Creates an array with ones of the integer type

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [67]:
np.ones(10, dtype='i2')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [68]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [69]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [70]:
np.zeros(5, dtype='i')

array([0, 0, 0, 0, 0], dtype=int32)

In [71]:
np.zeros([2, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [72]:
np.empty(20) # Empty array 

array([4.33603046e-315, 0.00000000e+000, 5.81212897e-317, 4.33620872e-315,
       5.80901438e-317, 5.80842941e-317, 5.80844522e-317, 5.80823969e-317,
       5.66812662e-317, 6.71869776e-310, 6.71869890e-310, 5.83435797e-317,
       6.71869776e-310, 5.83167421e-317, 6.71869775e-310, 6.71869775e-310,
       6.71869777e-310, 5.83659115e-317, 6.71869776e-310, 4.33622279e-315])

In [73]:
np.eye(4) # n-dimensional identity array 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [74]:
b

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [75]:
np.ones_like(b) # Array with the shape of array b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Random numbers

In [76]:
np.random.random((3,4))

array([[0.8544156 , 0.90101659, 0.00377184, 0.94560939],
       [0.65248278, 0.85271203, 0.18528778, 0.42444075],
       [0.87351141, 0.77100012, 0.85780241, 0.73107788]])

In [77]:
rng = np.random.default_rng(413)  # Starts the random number generator with seed=413

In [78]:
rng.random((3, 4)) # random number array between 0 and 1  with (shape)

array([[0.04622048, 0.48625808, 0.03210341, 0.07850197],
       [0.99893742, 0.79251717, 0.14096539, 0.20539366],
       [0.39306974, 0.14090258, 0.99557315, 0.68259742]])

In [79]:
rng.integers(1, 10, (3, 10)) # (min, max, shape)

array([[4, 4, 5, 9, 6, 3, 6, 7, 4, 2],
       [7, 5, 9, 1, 4, 1, 3, 4, 2, 4],
       [9, 6, 2, 2, 6, 8, 1, 4, 3, 9]])

In [80]:
rng.uniform(0, 5, (2,5)) # Samples are uniformly distributed over the interval (min, max, shape)

array([[4.6239944 , 3.26359437, 2.9543661 , 2.97639479, 3.62314861],
       [4.6588422 , 3.35944474, 0.31380207, 0.32887797, 2.54815115]])

## Changing the shape of an array

In [81]:
c = np.arange(16)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [82]:
c.reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [83]:
g = np.array([0,1,2,3])
g

array([0, 1, 2, 3])

In [84]:
g.shape

(4,)

In [85]:
newg = g[:, np.newaxis]  # inserts a new axis, making it two dimensional
newg

array([[0],
       [1],
       [2],
       [3]])

In [86]:
newg.shape

(4, 1)

Flatten an array

In [87]:
b

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [88]:
b.ravel()

array([1., 4., 7., 2., 5., 8., 3., 6., 9.])

In [89]:
b

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

## Universal Functions (`ufunc`)

A `ufunc` is a **vectorized wrapper** for a function that takes as inputs the components of an array and returns an equalnumber of outputs.
- Math operations (`add()`, `subtract()`, `square()`, `log10()`, ...)
- Trigonometric functions (`sin()`, `cos()`, `tan()`, `deg2rad()`, ...)
- Comparison functions (`greater()`, `less_equal()`, `fmax()`, ...)

The universal functions all are subclasses of `np.ufunc`

In [90]:
type(np.cos)  # they all are subclasses of np.ufunc

numpy.ufunc

In [91]:
b

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [92]:
np.sqrt(b)

array([[1.        , 2.        , 2.64575131],
       [1.41421356, 2.23606798, 2.82842712],
       [1.73205081, 2.44948974, 3.        ]])

In [93]:
np.cos(b)

array([[ 0.54030231, -0.65364362,  0.75390225],
       [-0.41614684,  0.28366219, -0.14550003],
       [-0.9899925 ,  0.96017029, -0.91113026]])

## Creating your own `ufunc` 
It is possible to create a new `ufunc` using `np.frompyfunc(func, nin, nout)`

In [94]:
x = rng.integers(0, 100, 10)
x

array([50, 97, 81, 29, 31, 94, 73, 46, 56, 15])

In [95]:
def f(x):
    return 1 if x > 23 else 0

In [96]:
f(x) # This will raise an error of interpretation

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
uf = np.frompyfunc(f, 1, 1)

In [ ]:
uf(x)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0], dtype=object)

In [ ]:
uf(50)

1

## Copies of an array

In [ ]:
original = np.arange(10)
original

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ref_to_original = original # The new object will point to `original`
ref_to_original

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ref_to_original[2]= 100
ref_to_original

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9])

In [ ]:
original

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9])

In [ ]:
ref_to_original[2] = 99

original   # changing `ref_to_original` has changed `original` !!!!

array([ 0,  1, 99,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
original = np.arange(10)

copy_of_original = np.copy(original) # Create a copy of the array
copy_of_original

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
copy_of_original[2] = 99

copy_of_original, original   # changing `copy_of_original` doesn't change `original` !!!!

(array([ 0,  1, 99,  3,  4,  5,  6,  7,  8,  9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
original = np.arange(10)

single_value = original[5]  # single element access returns a copy
single_value

np.int64(5)

In [ ]:
single_value = 9999
original             # not affected when `single_value` is changed

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Slices

In [ ]:
original = np.arange(10)

a_slice = original[2:4]    # slice of original
a_slice

array([2, 3])

In [ ]:
a_slice[1] = 1000  # changing elements of `a_slice` changes to `original`
a_slice, original

(array([   2, 1000]),
 array([   0,    1,    2, 1000,    4,    5,    6,    7,    8,    9]))

In [ ]:
original[3:6] = [101, 102, 103]   # changing 'original' also changes 'slice'
a_slice

array([  2, 101])

## Speed Comparisons

In [ ]:
import numpy as np

def my_mean(numbers):
    s = 0
    N = len(numbers)
    for i in range(N):
        s += numbers[i]
    return s/N

numbers = np.arange(1000000)
%timeit my_mean(numbers)

68.7 ms ± 864 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
def my_mean(numbers):
    return sum(numbers)/len(numbers)

numbers = list(range(1000000))
%timeit my_mean(numbers) # Defined function

4.89 ms ± 350 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
numbers = np.arange(1000000)
%timeit np.mean(numbers) # Numpy function

746 μs ± 4.76 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [ ]:
#conda install -n astrocom numba, no tengo conda xd
!pip install numba #instala numba en mi venv (astro-env)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 38.6 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 14.1 MB/s eta 0:00:0000:0100:01


In [100]:
import numba as nb

@nb.jit
def my_mean(numbers):
    s = 0
    N = len(numbers)
    for i in range(N):
        s += numbers[i]
    return s/N

numbers = np.arange(1000000)
%timeit my_mean(numbers)

164 μs ± 75.1 μs per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Speed Comparisons

In [ ]:
def my_sum(N):
    s = 0
    for i in range(N):
        s +=i
    return s

%timeit my_sum(100000000)

2.94 s ± 57.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
numbers_to_sum = np.arange(100000000)
%timeit np.sum(numbers_to_sum)

44 ms ± 218 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
@nb.jit
def my_sum(N):
    s = 0
    for i in range(N):
        s +=i
    return s

%timeit my_sum(100000000)

114 ns ± 0.833 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


Use of built-in function is encouraged !!!